name: Package Application with Pyinstaller

on:
  push:
    branches: [ "main-py" ]
  pull_request:
    branches: [ "main-py" ]
    
# adapted from https://github.com/pyinstaller/pyinstaller/issues/6296#issuecomment-943620645
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest'] # , 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - run: |
        pip install -r src/requirements.txt pyinstaller
        pyinstaller src/bsptexremap.spec
    # Optionally verify that it works (provided that it does not need user interaction)
    # - run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v2
      with:
        path: |
          *.txt
          *.fgd
          dist/*
          
